# Generated by Django 5.1.5 on 2025-01-28 07:36

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='patient',
            name='alcohol_amount',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='¿Cuánto?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergic_to_substances',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, null=True, verbose_name='¿Es alérgico a alguna sustancia, alimento o droga?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies_detail',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='¿A qué?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='attach_medical_report',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, null=True, verbose_name='Adjunta el informe médico'),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha De Nacimiento'),
        ),
        migrations.AddField(
            model_name='patient',
            name='bleeding_gums',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, null=True, verbose_name='¿Le sangran las encías?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='brushing_frequency',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='¿Cuántas veces al día se cepilla los dientes?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='cheeks_condition',
            field=models.CharField(blank=True, choices=[('abnormal', 'Anormal'), ('normal', 'Normal')], default='normal', max_length=10, null=True, verbose_name='Carillos'),
        ),
        migrations.AddField(
            model_name='patient',
            name='cigarettes_per_day',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='¿Cuántos al día?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='conditions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cardiac_problems', 'Problemas Cardiacos'), ('high_blood_pressure', 'Presión Sanguínea Alta'), ('low_blood_pressure', 'Presión Sanguínea Baja'), ('venereal_diseases', 'Enfermedades Venéreas'), ('hepatitis', 'Hepatitis'), ('stomach_ulcers', 'Úlceras Estomacales'), ('headaches', 'Dolor De Cabeza'), ('aids', 'Sida'), ('epilepsy', 'Epilepsia'), ('arthritis', 'Artritis'), ('diabetes', 'Diabetes'), ('nervous_issues', 'Alteraciones nerviosas'), ('sinusitis', 'Sinusitis'), ('other', 'Otras')], default='', max_length=172, null=True, verbose_name='Afecciones'),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Diagnóstico'),
        ),
        migrations.AddField(
            model_name='patient',
            name='difficulty_chewing',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, null=True, verbose_name='¿Para masticar?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='difficulty_opening_mouth',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, null=True, verbose_name='¿Para abrir la boca?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='difficulty_speaking',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, null=True, verbose_name='¿Tiene dificultad para hablar?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='difficulty_swallowing',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, null=True, verbose_name='¿Para tragar los alimentos?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='drinks_alcohol',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, null=True, verbose_name='¿Toma alcohol?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='floor_of_mouth_condition',
            field=models.CharField(blank=True, choices=[('abnormal', 'Anormal'), ('normal', 'Normal')], default='normal', max_length=10, null=True, verbose_name='Piso de la boca'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gingival_tissue_condition',
            field=models.CharField(blank=True, choices=[('abnormal', 'Anormal'), ('normal', 'Normal')], default='normal', max_length=10, null=True, verbose_name='Tejido gingival – periodontal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospitalization_reason',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='¿Por qué?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospitalized_last_2_years',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, null=True, verbose_name='¿Ha sido hospitalizado en los últimos dos años?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='identity_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número De Identidad'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_pregnant',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, null=True, verbose_name='¿Está embarazada?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='lips_condition',
            field=models.CharField(blank=True, choices=[('abnormal', 'Anormal'), ('normal', 'Normal')], default='normal', max_length=10, null=True, verbose_name='Labios'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_condition',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='¿Sí, qué enfermedad?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio / Colonia / Residencial'),
        ),
        migrations.AddField(
            model_name='patient',
            name='number_of_teeth',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de dientes presentes'),
        ),
        migrations.AddField(
            model_name='patient',
            name='observations',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='patient',
            name='oral_hygiene_status',
            field=models.CharField(blank=True, choices=[('good', 'Buena'), ('regular', 'Regular'), ('poor', 'Mala')], default='good', max_length=10, null=True, verbose_name='¿Estado de la higiene bucal?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar De Procedencia'),
        ),
        migrations.AddField(
            model_name='patient',
            name='periodontal_disease',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, null=True, verbose_name='Enfermedad periodontal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='periodontal_disease_location',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='¿Dónde? (si es localizada)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pregnancy_months',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='¿Cuántos meses?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pus_in_mouth',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, null=True, verbose_name='¿Le sale pus de algún lugar de la boca?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pus_location',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='¿Dónde?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='regular_medications',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='¿Qué medicamentos consume habitualmente?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relación / Parentesco'),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Del Responsable'),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Del Responsable'),
        ),
        migrations.AddField(
            model_name='patient',
            name='smokes',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, null=True, verbose_name='¿Fuma?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='tartar_presence',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, null=True, verbose_name='Presencia de sarro'),
        ),
        migrations.AddField(
            model_name='patient',
            name='tongue_condition',
            field=models.CharField(blank=True, choices=[('abnormal', 'Anormal'), ('normal', 'Normal')], default='normal', max_length=10, null=True, verbose_name='Lengua'),
        ),
        migrations.AddField(
            model_name='patient',
            name='tooth_mobility',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, null=True, verbose_name='¿Tiene movilidad en algún diente?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment_plan',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Plan de Tratamiento'),
        ),
        migrations.AddField(
            model_name='patient',
            name='under_medical_treatment',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=3, null=True, verbose_name='¿Está bajo tratamiento médico por enfermedad?'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dentista'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre Del Paciente'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_appointment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próxima Cita'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
