# Generated by Django 5.1.5 on 2025-02-03 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_patient_tooth_1_patient_tooth_10_patient_tooth_11_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dentist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_1',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 1'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_10',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 10'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_11',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 11'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_12',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 12'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_13',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 13'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_14',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 14'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_15',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 15'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_16',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 16'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_17',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 17'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_18',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 18'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_19',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 19'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_2',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 2'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_20',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 20'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_21',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 21'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_22',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 22'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_23',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 23'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_24',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 24'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_25',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 25'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_26',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 26'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_27',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 27'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_28',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 28'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_29',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 29'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_3',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 3'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_30',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 30'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_31',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 31'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_32',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 32'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_4',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 4'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_5',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 5'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_6',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 6'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_7',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 7'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_8',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 8'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tooth_9',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('R', 'R'), ('C', 'C'), ('-', '-'), ('X', 'X'), ('EI', 'EI'), ('P', 'P'), ('E', 'E'), ('PR', 'PR'), ('I', 'I'), ('FR', 'FR'), ('S', 'S'), ('PP', 'PP'), ('PC', 'PC')], max_length=2, null=True, verbose_name='Diente 9'),
        ),
    ]
