# Generated by Django 5.1.5 on 2025-02-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_dentist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
