# Generated by Django 5.1.5 on 2025-02-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='next_appointment',
        ),
    ]
