# Generated by Django 5.1.5 on 2025-02-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_patient_next_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_completed',
        ),
    ]
